apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: configserver
  type: LoadBalancer
