spring.main.allow-bean-definition-overriding: true

server:
  port: 8082
  
spring:
  cloud:
    config:
      server:
        jdbc:
          sql: select KEY, VALUE from CONFIG.PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://192.168.31.154:5432/postgres?CONFIG
    username: postgres
    password: docker 

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
