spring.main.allow-bean-definition-overriding: true

server:
  port: 8082
  
spring:
  cloud:
    config:
      server:
        jdbc:
          sql: select KEY, VALUE from CONFIG.PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://POSTGRES_URL:5432/postgres?CONFIG
    username: POSTGRES_USERNAME
    password: POSTGRES_PWD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
